### ISSUE TITLE
Turn off help-block

### ISSUE THREAD

**Issue by jonkristian** [manavo/laravel-bootstrap-forms#4]
Hi, would it be possible to get a configuration file published to allow turning off help-block, or turn off help-block in each openGroup, for instance:

```Form::openGroup('address', 'Address', array('class' => 'some-class', 'help-block' => 'off'))```

Visually on some fields i'd like to display the red border only.

**Comment by manavo** [comment]
Thanks to @vsposato's work in #7, you can now pass ```errorBlock``` (```true```/```false```) to options.
